org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Desactiva la compilación incremental de Kotlin para evitar conflictos de caché
kotlin.incremental=false
# Desactiva la caché de compilación de Gradle para mayor estabilidad
org.gradle.caching=false